//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaptik
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvKamp
    {
        public int id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string ohvat { get; set; }
        public string pokaz { get; set; }
        public string price { get; set; }
    }
}
