//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaptik
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetAdv
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Budget { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
