//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaptik
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckSys
    {
        public int id { get; set; }
        public Nullable<int> GoogleAct { get; set; }
        public Nullable<int> YaAct { get; set; }
        public Nullable<int> VKAct { get; set; }
    }
}
