//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaptik
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoard
    {
        public int id { get; set; }
        public string Day { get; set; }
        public string PriceM { get; set; }
        public string Click { get; set; }
        public string SeePage { get; set; }
        public string PriceZ { get; set; }
    }
}
