//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaptik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinaptikEntities2 : DbContext
    {
        public SinaptikEntities2()
            : base("name=SinaptikEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvComp> AdvComp { get; set; }
        public virtual DbSet<AdvertisingСompany> AdvertisingСompany { get; set; }
        public virtual DbSet<Autorization> Autorization { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<PlaceForAdv> PlaceForAdv { get; set; }
        public virtual DbSet<StatusAdv> StatusAdv { get; set; }
        public virtual DbSet<StrategyAdv> StrategyAdv { get; set; }
        public virtual DbSet<TypeAdv> TypeAdv { get; set; }
    }
}
