//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinaptik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int id { get; set; }
        public string idClients { get; set; }
        public string idAdvComp { get; set; }
        public Nullable<int> price { get; set; }
    }
}
